### ISSUE TITLE
Config for skip verify tls

### ISSUE THREAD

**Issue by Patcharaporn11** [strapi-community/strapi-plugin-redis#12]
example in commad
redis-cli -h {host}  --user {user} -a {pass} -c --tls

Is it possible to tls just enable but not verify?

**Comment by derrickmehaffy** [comment]
Hey @Patcharaporn11 I believe inside of the TLS object you can set the `rejectunauthorized` to false like:

```
module.exports = {
  redis: {
    config: {
      connections: {
        default: {
          connection: {
            // @see https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options
            host: '127.0.0.1',
            port: 6379,
            db: 0,
            user: 'username',
            password: 'secret',
            // @see https://github.com/luin/ioredis#tls-options
            tls: { 
              rejectunauthorized: false,
            },
          },
          settings: {
            debug: false,
          },
        },
      },
    },
  },
};
```

FYI none of these settings are directly controlled by the plugin since all the plugin does is mount an ioredis client on the global API. I found this key just searching through some of the ioredis team's tests:

https://github.com/luin/ioredis/blob/92aefaac13f42ad14986fde47c640ff8edc415ef/test/unit/connectors/connector.ts#L35

**Comment by Patcharaporn11** [comment]
It's working for me.

Thanks @derrickmehaffy
